### ISSUE TITLE
duplicate script tags in root page

### ISSUE THREAD

**Issue by 1bpm** [AJFaraday/smiff_music#11]
The rendered html of the main page contains duplicate script tags. After (/assets/)sound/patterns.js, the order is:
sound/pattern.js , 
sound/sample.js, 
sound/sound.js, 
application.js , 
sound/sound.js ,
sound/sample.js ,
sound/pattern.js

using Ruby 1.9.3 / Rails 4.1.0

**Comment by AJFaraday** [comment]
It looks like these didn't need to be manually added in the layout in Rails 4.2 

I've removed the manual declaration and they are now loaded once.
