### ISSUE TITLE
Can't play A# 3 it said it could play

### ISSUE THREAD

**Issue by sfcgeorge** [AJFaraday/smiff_music#24]
> > play C 3 on step 15
> Sorry, that's too low for sine to play, it only goes down to A# 3
> > play A# 3 on step 15
> Sorry, I couldn't run this action. Something nasty and technical happened. Tweet @MarmiteJunction about it.

**Comment by AJFaraday** [comment]
There was an issue with sharp notes with a space between the note and the octave number. 

SMIFF can and should support this.

Fixed now
